# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-06 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=40, verbose_name='Apellido')),
                ('edad', models.CharField(max_length=5, verbose_name='Edad')),
            ],
        ),
    ]
