# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import recipes.functions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190603_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, max_length=650, null=True, verbose_name='Descripción')),
                ('image', models.FileField(upload_to=recipes.functions.get_recipe_image_folder, verbose_name='Imagen')),
                ('ingredients', models.ManyToManyField(related_name='ingredients', to='recipes.Ingredient', verbose_name='ingredients')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
